name: StackHawk Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Secrets
        env:
          HAWK_API_KEY: ${{ secrets.HAWK_API_KEY }}
        run: |
          echo "Checking API key..."
          if [ -z "$HAWK_API_KEY" ]; then
            echo "Error: HAWK_API_KEY is empty"
            exit 1
          fi
          echo "API key exists (first 4 chars: ${HAWK_API_KEY:0:4})"

      - name: Run StackHawk Scan
        run: |
          echo "Running StackHawk scan..."
          docker run --rm \
            -e HAWK_API_KEY="${{ secrets.HAWK_API_KEY }}" \
            -v "$(pwd):/hawk" \
            stackhawk/hawkscan:latest \
            scan \
            --application-id 7d9f8efa-b061-4e2e-9fe3-0ce02e950357 \
            /hawk/stackhawk.yml
