name: StackHawk Scan
on: [push]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stackhawk/hawkscan-action@v1.2.0 
        with:
          hawk_api_key: ${{ secrets.HAWK_API_KEY }}
          app_id: 7d9f8efa-b061-4e2e-9fe3-0ce02e950357
