name: StackHawk Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run StackHawk Scan on Local Machine
        run: |
          ssh -o StrictHostKeyChecking=no user@10.0.2.15 << 'EOF'
            echo "Running StackHawk scan on local machine..."
            # Run StackHawk scan with the correct configuration
            hawk scan 
          EOF
