name: StackHawk Scan
on: [push]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate Secrets
        run: |
          echo "Checking API key..."
          [ -z "${{ secrets.HAWK_API_KEY }}" ] && echo "Error: HAWK_API_KEY is empty" && exit 1
          echo "API key exists (first 4 chars: ${${{ secrets.HAWK_API_KEY }}:0:4})"
          
      - name: Run StackHawk Scan
        run: |
          docker run --rm \
            -e HAWK_API_KEY=${{ secrets.HAWK_API_KEY }} \
            -e SHAWK_APP_ID=7d9f8efa-b061-4e2e-9fe3-0ce02e950357 \
            -v $(pwd):/hawk \
            stackhawk/hawkscan:1.2.0 \
            scan \
            /hawk/stackhawk.yml
