name: StackHawk Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run StackHawk Scan
        run: |
          echo "Running StackHawk scan..."
          echo "Using hardcoded API key (first 4 chars): hawk"
          
          docker run --rm \
            -e HAWK_API_KEY="hawk.AaiQ5DnvyXTTNItzOy8i.9UOSoCnj4plBrkQfFzkg" \
            -v "$(pwd):/hawk" \
            stackhawk/hawkscan:latest \
            scan \
            --application-id 7d9f8efa-b061-4e2e-9fe3-0ce02e950357 \
            /hawk/stackhawk.yml \
            --debug
