name: StackHawk Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run StackHawk Scan on Local Machine
        run: |
          ssh -o StrictHostKeyChecking=no user@your-local-machine-ip << 'EOF'
            echo "Running StackHawk scan on local machine..."
            # Ensure the StackHawk CLI is installed
            npm install -g @stackhawk/hawkscan
            # Run StackHawk scan with the correct configuration
            hawkscan scan --config /path/to/your/stackhawk.yml --api-key "hawk.AaiQ5DnvyXTTNItzOy8i.9UOSoCnj4plBrkQfFzkg"
          EOF
